[global]
# Global configuration for Streamlit

[server]
# Server configuration for Cloud Run
port = 8080
address = "0.0.0.0"
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200
maxMessageSize = 200

[browser]
# Browser configuration
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 8080

[theme]
# Theme configuration
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[client]
# Client configuration
showErrorDetails = true
caching = true
displayEnabled = true

[runner]
# Runner configuration
magicEnabled = true
installTracer = false
fixMatplotlib = true

[logger]
# Logger configuration
level = "info"
messageFormat = "%(asctime)s %(message)s"

[deprecation]
# Deprecation warnings
showfileUploaderEncoding = false
showPyplotGlobalUse = false 